server:
    error:
        include-message: always
    port: ${SERVER_PORT}
spring:
    application:
        name: appa
    datasource:
        url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
        schemas: public
        locations: filesystem:db/migration