CREATE SEQUENCE IF NOT EXISTS roles_id_seq INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS services_id_seq INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq INCREMENT BY 1;

CREATE TABLE carriages
(
    service_id  BIGINT                      NOT NULL,
    description VARCHAR(200)                NOT NULL,
    pick_up     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT carriages_pkey PRIMARY KEY (service_id)
);

CREATE TABLE guides
(
    id                 CHAR(36)    NOT NULL,
    current_checkpoint VARCHAR(50) NOT NULL,
    current_nation     VARCHAR(50) NOT NULL,
    service_id         BIGINT      NOT NULL,
    CONSTRAINT guides_pkey PRIMARY KEY (id)
);

CREATE TABLE packages
(
    service_id BIGINT  NOT NULL,
    height     INTEGER NOT NULL,
    length     INTEGER NOT NULL,
    weight     INTEGER NOT NULL,
    width      INTEGER NOT NULL,
    CONSTRAINT packages_pkey PRIMARY KEY (service_id)
);

CREATE TABLE roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(250)                            NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE services
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    arrived                TIMESTAMP WITHOUT TIME ZONE,
    created                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    destination_checkpoint VARCHAR(50)                             NOT NULL,
    destination_nation     VARCHAR(50)                             NOT NULL,
    origin_checkpoint      VARCHAR(50)                             NOT NULL,
    origin_nation          VARCHAR(50)                             NOT NULL,
    price                  DOUBLE PRECISION                        NOT NULL,
    type                   VARCHAR(20)                             NOT NULL,
    user_bison             BIGINT,
    user_citizen           BIGINT                                  NOT NULL,
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    available BOOLEAN DEFAULT TRUE                    NOT NULL,
    document  VARCHAR(50),
    email     VARCHAR(50)                             NOT NULL,
    name      VARCHAR(50)                             NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    phone     VARCHAR(25),
    vehicle   VARCHAR(10),
    role_id   BIGINT,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE guides
    ADD CONSTRAINT uk_169rchxd0s03evik6qeufm2g4 UNIQUE (service_id);

ALTER TABLE users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uk_du5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uk_kgnb8tmua5cirywqjj4m3id0l UNIQUE (document);

ALTER TABLE roles
    ADD CONSTRAINT uk_ofx66keruapi6vyqpv6f2or37 UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uk_oho9r5tn6ajs6k24itpc3ldtg UNIQUE (vehicle);

ALTER TABLE services
    ADD CONSTRAINT fk3viurfysdfnyk3l81eqow51eg FOREIGN KEY (user_citizen) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE carriages
    ADD CONSTRAINT fk8ecs9q6jog2378nq5u3rbgf2l FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE NO ACTION;

ALTER TABLE services
    ADD CONSTRAINT fkfqilpga610pslhekx65c6eq1w FOREIGN KEY (user_bison) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE guides
    ADD CONSTRAINT fknrr7ywcjxvlhjxvyuef2esr3c FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE NO ACTION;

ALTER TABLE packages
    ADD CONSTRAINT fkryghicfhkpk9bm19bsa7f91i1 FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE NO ACTION;